/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Minggu10;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rizki
 */
public class Supplier extends javax.swing.JFrame {

    private Connection con;
    private Statement stm;
    private ResultSet RSsupplier;
    private String sql, KodeSup, NamaPerus, NamaBrg, NoTlp, Alamat;

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        ShowData(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelKodeSup = new javax.swing.JLabel();
        TxtKodeSup = new javax.swing.JTextField();
        LabelNamaPer = new javax.swing.JLabel();
        TxtNamaPer = new javax.swing.JTextField();
        LabelNamaBrg = new javax.swing.JLabel();
        TxtNamaBrg = new javax.swing.JTextField();
        LabelNoTlp = new javax.swing.JLabel();
        TxtNoTlp = new javax.swing.JTextField();
        LabelAlamat = new javax.swing.JLabel();
        TxtAlamat = new javax.swing.JTextField();
        ButtonSave = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(935, 598));
        setMinimumSize(new java.awt.Dimension(935, 598));

        jPanel1.setBackground(new java.awt.Color(2, 1, 101));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Supplier", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel1.setMaximumSize(new java.awt.Dimension(935, 575));
        jPanel1.setMinimumSize(new java.awt.Dimension(935, 575));

        LabelKodeSup.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelKodeSup.setForeground(new java.awt.Color(255, 255, 255));
        LabelKodeSup.setText("Kode Supplier");

        TxtKodeSup.setBackground(new java.awt.Color(255, 255, 255));
        TxtKodeSup.setForeground(new java.awt.Color(0, 0, 0));
        TxtKodeSup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtKodeSup.setName(""); // NOI18N

        LabelNamaPer.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelNamaPer.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaPer.setText("Nama Perusahaan");

        TxtNamaPer.setBackground(new java.awt.Color(255, 255, 255));
        TxtNamaPer.setForeground(new java.awt.Color(0, 0, 0));
        TxtNamaPer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtNamaPer.setName(""); // NOI18N

        LabelNamaBrg.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelNamaBrg.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaBrg.setText("Barang Di Jual");

        TxtNamaBrg.setBackground(new java.awt.Color(255, 255, 255));
        TxtNamaBrg.setForeground(new java.awt.Color(0, 0, 0));
        TxtNamaBrg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtNamaBrg.setName(""); // NOI18N

        LabelNoTlp.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelNoTlp.setForeground(new java.awt.Color(255, 255, 255));
        LabelNoTlp.setText("No Tlp");

        TxtNoTlp.setBackground(new java.awt.Color(255, 255, 255));
        TxtNoTlp.setForeground(new java.awt.Color(0, 0, 0));
        TxtNoTlp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtNoTlp.setName(""); // NOI18N

        LabelAlamat.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelAlamat.setForeground(new java.awt.Color(255, 255, 255));
        LabelAlamat.setText("Alamat");

        TxtAlamat.setBackground(new java.awt.Color(255, 255, 255));
        TxtAlamat.setForeground(new java.awt.Color(0, 0, 0));
        TxtAlamat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtAlamat.setName(""); // NOI18N

        ButtonSave.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSave.setForeground(new java.awt.Color(0, 0, 0));
        ButtonSave.setText("SAVE");
        ButtonSave.setBorder(null);
        ButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonSave.setMaximumSize(new java.awt.Dimension(65, 22));
        ButtonSave.setMinimumSize(new java.awt.Dimension(65, 22));
        ButtonSave.setPreferredSize(new java.awt.Dimension(65, 22));
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        ButtonEdit.setBackground(new java.awt.Color(255, 255, 255));
        ButtonEdit.setForeground(new java.awt.Color(0, 0, 0));
        ButtonEdit.setText("EDIT");
        ButtonEdit.setBorder(null);
        ButtonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEdit.setMaximumSize(new java.awt.Dimension(65, 22));
        ButtonEdit.setMinimumSize(new java.awt.Dimension(65, 22));
        ButtonEdit.setPreferredSize(new java.awt.Dimension(65, 22));
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonClear.setBackground(new java.awt.Color(255, 255, 255));
        ButtonClear.setForeground(new java.awt.Color(0, 0, 0));
        ButtonClear.setText("CLEAR");
        ButtonClear.setBorder(null);
        ButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClear.setMaximumSize(new java.awt.Dimension(65, 22));
        ButtonClear.setMinimumSize(new java.awt.Dimension(65, 22));
        ButtonClear.setPreferredSize(new java.awt.Dimension(65, 22));
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        ButtonDelete.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDelete.setForeground(new java.awt.Color(0, 0, 0));
        ButtonDelete.setText("DELETE");
        ButtonDelete.setBorder(null);
        ButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonDelete.setMaximumSize(new java.awt.Dimension(65, 22));
        ButtonDelete.setMinimumSize(new java.awt.Dimension(65, 22));
        ButtonDelete.setPreferredSize(new java.awt.Dimension(65, 22));
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelKodeSup)
                        .addGap(71, 71, 71)
                        .addComponent(TxtKodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelNamaBrg)
                        .addGap(68, 68, 68)
                        .addComponent(TxtNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelNamaPer)
                        .addGap(45, 45, 45)
                        .addComponent(TxtNamaPer, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNoTlp)
                            .addComponent(LabelAlamat))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtKodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKodeSup)
                    .addComponent(TxtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNoTlp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtNamaPer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelAlamat)
                        .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelNamaPer))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNamaBrg)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Input Data");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        // TODO add your handling code here:
        KodeSup = String.valueOf(TxtKodeSup.getText());
        NamaPerus = String.valueOf(TxtNamaPer.getText());
        NamaBrg = String.valueOf(TxtNamaBrg.getText());
        NoTlp = String.valueOf(TxtNoTlp.getText());
        Alamat = String.valueOf(TxtAlamat.getText());
        try {
//            String url="jdbc:mysql://localhost/penjualan";
//            String user="root";
//            String pass="";
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            con=DriverManager.getConnection(url,user,pass);
            sql = "INSERT INTO supplier (kd_suplier, perusahaan, nama_barang, no_hp, alamat)value"
                    + "('" + KodeSup + "','" + NamaPerus + "','" + NamaBrg + "','" + NoTlp + "','" + Alamat + "')";
            stm = koneksi.konek();
            stm.execute(sql);
            Clear();
            ShowData(null);
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error \n" + e.getMessage());
        }
    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        KodeSup = String.valueOf(TxtKodeSup.getText());
        NamaPerus = String.valueOf(TxtNamaPer.getText());
        NamaBrg = String.valueOf(TxtNamaBrg.getText());
        NoTlp = String.valueOf(TxtNoTlp.getText());
        Alamat = String.valueOf(TxtAlamat.getText());
        try {
            sql = "update supplier set perusahaan='" + NamaPerus + "', nama_barang='" + NamaBrg + "', no_hp='" + NoTlp + "', alamat='" + Alamat + "'where kd_suplier='" + KodeSup + "'";
            stm = koneksi.konek();
            stm.execute(sql);
            Clear();
            ShowData(null);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Perbarui");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error \n" + e.getMessage());
        }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // TODO add your handling code here:
        try {
            sql = "delete from supplier where kd_suplier='" + String.valueOf(TxtKodeSup.getText()) + "'";
            stm = koneksi.konek();
            stm.execute(sql);
            Clear();
            ShowData(null);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error \n"+e.getMessage());
        }

    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris=jTable1.rowAtPoint(evt.getPoint());
        KodeSup=jTable1.getValueAt(baris, 1).toString();
        NamaPerus=jTable1.getValueAt(baris, 2).toString();
        NamaBrg=jTable1.getValueAt(baris, 3).toString();
        NoTlp=jTable1.getValueAt(baris, 4).toString();
        Alamat=jTable1.getValueAt(baris, 5).toString();
        TxtKodeSup.setText(KodeSup);
        TxtKodeSup.disable();
        if(jTable1.getValueAt(baris, 2)==null)TxtNamaPer.setText("");
        else TxtNamaPer.setText(NamaPerus);
        if(jTable1.getValueAt(baris, 3)==null)TxtNamaBrg.setText("");
        else TxtNamaBrg.setText(NamaBrg);
        if(jTable1.getValueAt(baris, 4)==null)TxtNoTlp.setText("");
        else TxtNoTlp.setText(NoTlp);
        if(jTable1.getValueAt(baris, 5)==null)TxtAlamat.setText("");
        else TxtAlamat.setText(Alamat);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_ButtonClearActionPerformed
    private void Clear() {
        TxtKodeSup.setText("");
        TxtNamaPer.setText("");
        TxtNamaBrg.setText("");
        TxtNoTlp.setText("");
        TxtAlamat.setText("");
        TxtKodeSup.enable(true);
        ShowData(null);
    }

    private void ShowData(String km) {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No");
        tbl.addColumn("Kode Supplier");
        tbl.addColumn("Nama Perusahaan");
        tbl.addColumn("Barang di Jual");
        tbl.addColumn("No Telp");
        tbl.addColumn("Alamat");
        try {
            int i = 1;
            stm = koneksi.konek();
            if (km != null) {
                sql = "INSERT * FROM supplier"
                        + "where kd_supplier like '%" + km + "%'";
            } else {
                sql = "SELECT * FROM supplier";
            }
            RSsupplier = stm.executeQuery(sql);
            while (RSsupplier.next()) {
                tbl.addRow(new Object[]{
                    ("" + i++),
                    RSsupplier.getString(1),
                    RSsupplier.getString(2),
                    RSsupplier.getString(3),
                    RSsupplier.getString(4),
                    RSsupplier.getString(5)
                });
            }
            jTable1.setModel(tbl);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error \n Gagal Memuat Ke Database \n Cek Kneksi dan Cek Database sudah di aktifkan atau belum");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonSave;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelKodeSup;
    private javax.swing.JLabel LabelNamaBrg;
    private javax.swing.JLabel LabelNamaPer;
    private javax.swing.JLabel LabelNoTlp;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtKodeSup;
    private javax.swing.JTextField TxtNamaBrg;
    private javax.swing.JTextField TxtNamaPer;
    private javax.swing.JTextField TxtNoTlp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
