/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Minggu10;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author rizki
 */
public class Supplier extends javax.swing.JFrame {

    private Connection con;
    private Statement stm;
    private ResultSet RSsupplier;
    private String sql, KodeSup, NamaPerus, NamaBrg, NoTlp, Alamat, km;
    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNoTrs = new javax.swing.JLabel();
        TxtKodeSup = new javax.swing.JTextField();
        ButtonSave = new javax.swing.JButton();
        LabelNoTrs1 = new javax.swing.JLabel();
        TxtNamaPer = new javax.swing.JTextField();
        LabelNoTrs2 = new javax.swing.JLabel();
        TxtNamaBrg = new javax.swing.JTextField();
        LabelNoTrs3 = new javax.swing.JLabel();
        TxtNoTlp = new javax.swing.JTextField();
        LabelNoTrs4 = new javax.swing.JLabel();
        TxtAlamat = new javax.swing.JTextField();
        ButtonAdd1 = new javax.swing.JButton();
        ButtonAdd2 = new javax.swing.JButton();
        ButtonAdd3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(935, 598));
        setMinimumSize(new java.awt.Dimension(935, 598));

        jPanel1.setBackground(new java.awt.Color(2, 1, 101));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Supplier", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel1.setMaximumSize(new java.awt.Dimension(935, 575));
        jPanel1.setMinimumSize(new java.awt.Dimension(935, 575));

        LabelNoTrs.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelNoTrs.setForeground(new java.awt.Color(255, 255, 255));
        LabelNoTrs.setText("Kode Supplier");

        TxtKodeSup.setBackground(new java.awt.Color(255, 255, 255));
        TxtKodeSup.setForeground(new java.awt.Color(0, 0, 0));
        TxtKodeSup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtKodeSup.setName(""); // NOI18N

        ButtonSave.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSave.setForeground(new java.awt.Color(0, 0, 0));
        ButtonSave.setText("SAVE");
        ButtonSave.setBorder(null);
        ButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonSave.setMaximumSize(new java.awt.Dimension(65, 22));
        ButtonSave.setMinimumSize(new java.awt.Dimension(65, 22));
        ButtonSave.setPreferredSize(new java.awt.Dimension(65, 22));
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        LabelNoTrs1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelNoTrs1.setForeground(new java.awt.Color(255, 255, 255));
        LabelNoTrs1.setText("Nama Perusahaan");

        TxtNamaPer.setBackground(new java.awt.Color(255, 255, 255));
        TxtNamaPer.setForeground(new java.awt.Color(0, 0, 0));
        TxtNamaPer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtNamaPer.setName(""); // NOI18N

        LabelNoTrs2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelNoTrs2.setForeground(new java.awt.Color(255, 255, 255));
        LabelNoTrs2.setText("Barang Di Jual");

        TxtNamaBrg.setBackground(new java.awt.Color(255, 255, 255));
        TxtNamaBrg.setForeground(new java.awt.Color(0, 0, 0));
        TxtNamaBrg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtNamaBrg.setName(""); // NOI18N

        LabelNoTrs3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelNoTrs3.setForeground(new java.awt.Color(255, 255, 255));
        LabelNoTrs3.setText("No Tlp");

        TxtNoTlp.setBackground(new java.awt.Color(255, 255, 255));
        TxtNoTlp.setForeground(new java.awt.Color(0, 0, 0));
        TxtNoTlp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtNoTlp.setName(""); // NOI18N

        LabelNoTrs4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelNoTrs4.setForeground(new java.awt.Color(255, 255, 255));
        LabelNoTrs4.setText("Alamat");

        TxtAlamat.setBackground(new java.awt.Color(255, 255, 255));
        TxtAlamat.setForeground(new java.awt.Color(0, 0, 0));
        TxtAlamat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        TxtAlamat.setName(""); // NOI18N

        ButtonAdd1.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAdd1.setForeground(new java.awt.Color(0, 0, 0));
        ButtonAdd1.setText("EDIT");
        ButtonAdd1.setBorder(null);
        ButtonAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAdd1.setMaximumSize(new java.awt.Dimension(65, 22));
        ButtonAdd1.setMinimumSize(new java.awt.Dimension(65, 22));
        ButtonAdd1.setPreferredSize(new java.awt.Dimension(65, 22));

        ButtonAdd2.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAdd2.setForeground(new java.awt.Color(0, 0, 0));
        ButtonAdd2.setText("CLEAR");
        ButtonAdd2.setBorder(null);
        ButtonAdd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAdd2.setMaximumSize(new java.awt.Dimension(65, 22));
        ButtonAdd2.setMinimumSize(new java.awt.Dimension(65, 22));
        ButtonAdd2.setPreferredSize(new java.awt.Dimension(65, 22));

        ButtonAdd3.setBackground(new java.awt.Color(255, 255, 255));
        ButtonAdd3.setForeground(new java.awt.Color(0, 0, 0));
        ButtonAdd3.setText("DELETE");
        ButtonAdd3.setBorder(null);
        ButtonAdd3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAdd3.setMaximumSize(new java.awt.Dimension(65, 22));
        ButtonAdd3.setMinimumSize(new java.awt.Dimension(65, 22));
        ButtonAdd3.setPreferredSize(new java.awt.Dimension(65, 22));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelNoTrs)
                        .addGap(71, 71, 71)
                        .addComponent(TxtKodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelNoTrs2)
                        .addGap(68, 68, 68)
                        .addComponent(TxtNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelNoTrs1)
                        .addGap(45, 45, 45)
                        .addComponent(TxtNamaPer, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNoTrs3)
                            .addComponent(LabelNoTrs4))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtKodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNoTrs)
                    .addComponent(TxtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNoTrs3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtNamaPer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelNoTrs4)
                        .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelNoTrs1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNoTrs2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Input Data");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        // TODO add your handling code here:
        KodeSup=String.valueOf(TxtKodeSup.getText());
        NamaPerus=String.valueOf(TxtNamaPer.getText());
        NamaBrg=String.valueOf(TxtNamaBrg.getText());
        NoTlp=String.valueOf(TxtNoTlp.getText());
        Alamat=String.valueOf(TxtAlamat.getText());
        try {
            String url="jdbc:mysql://localhost/penjualan";
            String user="root";
            String pass="";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection(url,user,pass);
            sql="INSERT INTO supplier (kd_suplier, perusahaan, nama_barang, no_hp, alamat)value"
                    + "('"+KodeSup+"','"+NamaPerus+"','"+NamaBrg+"','"+NoTlp+"','"+Alamat+"')";
            stm=con.createStatement();
            stm.execute(sql);
            Clear();
            ShowData(null);
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error \n"+e.getMessage());
        }
    }//GEN-LAST:event_ButtonSaveActionPerformed
    private void Clear(){
        TxtKodeSup.setText("");
        TxtNamaPer.setText("");
        TxtNamaBrg.setText("");
        TxtNoTlp.setText("");
        TxtAlamat.setText("");
        TxtKodeSup.enable(true);
        ShowData(null);
    }
    private void ShowData(String km){
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("No");
        tbl.addColumn("Kode Supplier");
        tbl.addColumn("Nama Perusahaan");
        tbl.addColumn("Barang di Jual");
        tbl.addColumn("No Telp");
        tbl.addColumn("Alamat");
        try {
            int i=1;
            stm=con.createStatement();
            if(km!=null){
                sql="INSERT * FROM supplier"
                        + "where kd_supplier like '%"+km+"%'";
            }else{
                sql="SELECT * FROM supplier";
            }
            RSsupplier=stm.executeQuery(sql);
            while(RSsupplier.next())
                tbl.addRow(new Object[]{
                    (""+i++),
                    RSsupplier.getString(1),
                    RSsupplier.getString(2),
                    RSsupplier.getString(3),
                    RSsupplier.getString(4),
                    RSsupplier.getString(5)
                });
            jTable1.setModel(tbl);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error \n Gagal Memuat Ke Database \n Cek Kneksi dan Cek Database sudah di aktifkan atau belum");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd1;
    private javax.swing.JButton ButtonAdd2;
    private javax.swing.JButton ButtonAdd3;
    private javax.swing.JButton ButtonSave;
    private javax.swing.JLabel LabelNoTrs;
    private javax.swing.JLabel LabelNoTrs1;
    private javax.swing.JLabel LabelNoTrs2;
    private javax.swing.JLabel LabelNoTrs3;
    private javax.swing.JLabel LabelNoTrs4;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtKodeSup;
    private javax.swing.JTextField TxtNamaBrg;
    private javax.swing.JTextField TxtNamaPer;
    private javax.swing.JTextField TxtNoTlp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
