/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Minggu9;
import java.awt.Color;
/**
 *
 * @author rizki
 */
public class Pembelian extends javax.swing.JPanel {

    /**
     * Creates new form Pembelian
     */
    public Pembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNoTrs = new javax.swing.JLabel();
        LabelTglTrs = new javax.swing.JLabel();
        LabelKodeBrg = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 1, 101));
        setMinimumSize(new java.awt.Dimension(935, 575));
        setPreferredSize(new java.awt.Dimension(935, 575));

        jPanel1.setBackground(new java.awt.Color(2, 1, 101));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Pembelian", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        LabelNoTrs.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelNoTrs.setForeground(new java.awt.Color(255, 255, 255));
        LabelNoTrs.setText("No Transaksi");

        LabelTglTrs.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelTglTrs.setForeground(new java.awt.Color(255, 255, 255));
        LabelTglTrs.setText("Tgl Transaksi");

        LabelKodeBrg.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LabelKodeBrg.setForeground(new java.awt.Color(255, 255, 255));
        LabelKodeBrg.setText("Kode Barang");

        Label3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Label3.setForeground(new java.awt.Color(255, 255, 255));
        Label3.setText("jLabel1");

        Label4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Label4.setForeground(new java.awt.Color(255, 255, 255));
        Label4.setText("jLabel1");

        Label5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Label5.setForeground(new java.awt.Color(255, 255, 255));
        Label5.setText("jLabel1");

        Label6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Label6.setForeground(new java.awt.Color(255, 255, 255));
        Label6.setText("jLabel1");

        Label7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Label7.setForeground(new java.awt.Color(255, 255, 255));
        Label7.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNoTrs)
                    .addComponent(LabelTglTrs)
                    .addComponent(LabelKodeBrg)
                    .addComponent(Label3)
                    .addComponent(Label4)
                    .addComponent(Label5)
                    .addComponent(Label6)
                    .addComponent(Label7))
                .addContainerGap(774, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(LabelNoTrs)
                .addGap(45, 45, 45)
                .addComponent(LabelTglTrs)
                .addGap(45, 45, 45)
                .addComponent(LabelKodeBrg)
                .addGap(45, 45, 45)
                .addComponent(Label3)
                .addGap(45, 45, 45)
                .addComponent(Label4)
                .addGap(45, 45, 45)
                .addComponent(Label5)
                .addGap(45, 45, 45)
                .addComponent(Label6)
                .addGap(45, 45, 45)
                .addComponent(Label7)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel LabelKodeBrg;
    private javax.swing.JLabel LabelNoTrs;
    private javax.swing.JLabel LabelTglTrs;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
